name: Process CSV file

on:
  workflow_dispatch:

jobs:
  process_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y csvkit

    - name: Process CSV file
      run: csvcut -c 1,2 file.csv > processed.csv

    - name: Commit processed file
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo
        cd repo
        git config user.email "github-actions@example.com"
        git config user.name "GitHub Actions"
        git add processed.csv
        git commit -m "Processed CSV file"
        git push origin HEAD:master


